apiVersion : apps/v1
kind: Deployment
metadata:
  name: gjuly23image1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gjuly23image1
  template:
    metadata:
      labels:
        app: gjuly23image1
    spec:
      containers:
        - name: gjuly23image1
          image: nginx
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: gjuly23image1
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: gjuly23image1
